version: "3.9"

services:
  backend:
    build: ./backend
    container_name: media-backend-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: media-db-dev
    restart: always
    environment:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: