services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: media-backend-dev
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.dev
    ports:
      - "8801:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: media-db-dev
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
