---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: media-backend
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - "./.env"
    ports:
    - '${APP_PORT}:8000'
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: media-db
    restart: always
    env_file:
      - "./.env"
    volumes:
      - "db_data:/var/lib/postgresql/data"
volumes:
  db_data:
