---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: media-backend
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - "./.env"
    ports:
      - '${APP_PORT}:8000'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: postgres:15
    container_name: media-db
    restart: always
    env_file:
      - "./.env"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$  {POSTGRES_USER} -d   $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
volumes:
  db_data:
