---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: media-backend-dev
    volumes:
      - "./backend:/app"
    env_file:
      - "./.env.dev"
    ports:
      - "8801:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
  db:
    image: postgres:15
    container_name: media-db-dev
    restart: always
    env_file:
      - "./.env.dev"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
