FROM python:3.12-slim

# Устанавливаем poetry
RUN pip install --no-cache-dir poetry

WORKDIR /app

# Копируем зависимости
COPY pyproject.toml poetry.lock* ./

# Устанавливаем все зависимости (включая dev)
RUN poetry install --no-root --no-interaction --no-ansi

# Копируем приложение
COPY . .

# Hot-reload режим
CMD ["poetry", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]