from enum import Enum


class SonarrErrorCode(str, Enum):
    SONARR_FETCH_FAILED = "SONARR_FETCH_FAILED"
    INVALID_DATE = "INVALID_DATE"
    NETWORK_ERROR = "NETWORK_ERROR"


class RadarrErrorCode(str, Enum):
    RADARR_FETCH_FAILED = "RADARR_FETCH_FAILED"
    NETWORK_ERROR = "NETWORK_ERROR"


class JellyfinErrorCode(str, Enum):
    JELLYFIN_FETCH_FAILED = "JELLYFIN_FETCH_FAILED"
    NETWORK_ERROR = "NETWORK_ERROR"
