"""add sync schedules

Revision ID: 01760f85b906
Revises: d1e2f3a4b5c6
Create Date: 2026-03-22 09:28:57.703742

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01760f85b906"
down_revision: Union[str, Sequence[str], None] = "d1e2f3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "JELLYFIN_USERS_IMPORT",
                "RADARR_IMPORT",
                "JELLYFIN_MOVIES_IMPORT",
                "JELLYFIN_MOVIE_WATCH_HISTORY",
                "SONARR_IMPORT",
                "JELLYFIN_SERIES_IMPORT",
                "JELLYFIN_SERIES_WATCH_HISTORY",
                name="syncjobtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "preset",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", "CUSTOM", name="schedulepreset"),
            nullable=False,
        ),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("is_running", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_type"),
    )
    op.create_index(op.f("ix_sync_schedules_id"), "sync_schedules", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_schedules_id"), table_name="sync_schedules")
    op.drop_table("sync_schedules")
    sa.Enum(name="syncjobtype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="schedulepreset").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
