"""add service_configs table

Revision ID: 318c76f4e023
Revises: a785246ff4d1
Create Date: 2026-03-21 07:00:50.115135

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "318c76f4e023"
down_revision: Union[str, Sequence[str], None] = "a785246ff4d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum("RADARR", "SONARR", "JELLYFIN", name="servicetype"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("encrypted_api_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_type"),
    )
    op.create_index(op.f("ix_service_configs_id"), "service_configs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_configs_id"), table_name="service_configs")
    op.drop_table("service_configs")
    sa.Enum(name="servicetype").drop(op.get_bind())
    # ### end Alembic commands ###
