"""update models for timezone and new fields

Revision ID: 3699efcdb808
Revises: a17003661b15
Create Date: 2025-09-27 09:01:24.535353
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3699efcdb808'
down_revision: Union[str, Sequence[str], None] = 'a17003661b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('jellyfin_user_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('jellyfin_user_id'),
        sa.UniqueConstraint('username')
    )
    op.create_table(
        'watch_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_id', sa.Integer(), nullable=False),
        sa.Column('episode_id', sa.Integer(), nullable=True),
        sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['episode_id'], ['episodes.id']),
        sa.ForeignKeyConstraint(['media_id'], ['media.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('episodes', sa.Column('jellyfin_id', sa.Integer(), nullable=True))
    op.add_column('episodes', sa.Column('air_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('episodes', 'watched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'episodes', ['jellyfin_id'])

    # media.created_at с дефолтным значением
    op.add_column(
        'media',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now()  # <-- дефолт для существующих строк
        )
    )
    op.alter_column('media', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('movies', sa.Column('radarr_id', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('watched', sa.Boolean(), nullable=True))
    op.add_column('movies', sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'movies', ['radarr_id'])
    op.add_column('seasons', sa.Column('jellyfin_id', sa.Integer(), nullable=True))
    op.add_column('seasons', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('seasons', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('seasons', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'seasons', ['jellyfin_id'])
    op.add_column('series', sa.Column('jellyfin_id', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('status', sa.String(), nullable=True))
    op.add_column('series', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('series', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'series', ['jellyfin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='unique')
    op.drop_column('series', 'finished_at')
    op.drop_column('series', 'started_at')
    op.drop_column('series', 'status')
    op.drop_column('series', 'jellyfin_id')
    op.drop_constraint(None, 'seasons', type_='unique')
    op.alter_column('seasons', 'release_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('seasons', 'finished_at')
    op.drop_column('seasons', 'started_at')
    op.drop_column('seasons', 'jellyfin_id')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'watched_at')
    op.drop_column('movies', 'watched')
    op.drop_column('movies', 'radarr_id')
    op.alter_column('media', 'release_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('media', 'created_at')
    op.drop_constraint(None, 'episodes', type_='unique')
    op.alter_column('episodes', 'watched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('episodes', 'air_date')
    op.drop_column('episodes', 'jellyfin_id')
    op.drop_table('watch_history')
    op.drop_table('users')
    # ### end Alembic commands ###
