"""added tmdb_id and imdb_id

Revision ID: 379e67d12bb9
Revises: 69e983b34c87
Create Date: 2025-10-24 17:58:19.293506

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "379e67d12bb9"
down_revision: Union[str, Sequence[str], None] = "69e983b34c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("tmdb_id", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("imdb_id", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("jellyfin_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "movies", ["jellyfin_id"])
    op.create_unique_constraint(None, "movies", ["imdb_id"])
    op.create_unique_constraint(None, "movies", ["tmdb_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="unique")
    op.drop_constraint(None, "movies", type_="unique")
    op.drop_constraint(None, "movies", type_="unique")
    op.drop_column("movies", "jellyfin_id")
    op.drop_column("movies", "imdb_id")
    op.drop_column("movies", "tmdb_id")
    # ### end Alembic commands ###
