"""rename_type_to_media_type

Revision ID: 3b6ead0c844e
Revises: 3699efcdb808
Create Date: 2025-10-12 15:39:20.621740

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b6ead0c844e"
down_revision: Union[str, Sequence[str], None] = "3699efcdb808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("episodes", "watched", existing_type=sa.BOOLEAN(), nullable=False)
    op.add_column(
        "media",
        sa.Column("media_type", sa.Enum("MOVIE", "SERIES", name="mediatype"), nullable=False),
    )
    op.drop_column("media", "type")
    op.alter_column("movies", "watched", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movies", "watched", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "media",
        sa.Column(
            "type",
            postgresql.ENUM("MOVIE", "SERIES", name="mediatype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("media", "media_type")
    op.alter_column("episodes", "watched", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
