"""make episode.sonarr_id nullable

Revision ID: 4257ec3d4ecd
Revises: 5552c6430756
Create Date: 2025-11-08 17:15:40.140159

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4257ec3d4ecd"
down_revision: Union[str, Sequence[str], None] = "5552c6430756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("episodes", "sonarr_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("episodes", "sonarr_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
