"""update models for jellyfin_id str64

Revision ID: 5e69e8ebe3ea
Revises: 4257ec3d4ecd
Create Date: 2025-11-08 18:13:31.050457

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e69e8ebe3ea"
down_revision: Union[str, Sequence[str], None] = "4257ec3d4ecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
