"""Change jellyfin_user_id to VARCHAR(36)

Revision ID: 69e983b34c87
Revises: e0e03248ff4a
Create Date: 2025-10-23 12:58:23.586532

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69e983b34c87"
down_revision: Union[str, Sequence[str], None] = "e0e03248ff4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "jellyfin_user_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "jellyfin_user_id",
        existing_type=sa.String(length=36),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
