"""update models for series added field sonarr_id

Revision ID: 844e6abd66a2
Revises: 3b6ead0c844e
Create Date: 2025-10-18 17:13:14.506128

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "844e6abd66a2"
down_revision: Union[str, Sequence[str], None] = "3b6ead0c844e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("series", sa.Column("sonarr_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "series", ["sonarr_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "series", type_="unique")
    op.drop_column("series", "sonarr_id")
    # ### end Alembic commands ###
