"""add unique constraint
  to watch_history

Revision ID: 9afc76d62278
Revises: 9f8e7d6c5b4a
Create Date: 2026-06-07 11:32:44.844286

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9afc76d62278"
down_revision: Union[str, Sequence[str], None] = "9f8e7d6c5b4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_watch_history_user_media_episode",
        "watch_history",
        ["user_id", "media_id", "episode_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_watch_history_user_media_episode", "watch_history", type_="unique")
    # ### end Alembic commands ###
