"""add tmdb metadata fields to movies and TMDB_MOVIES_METADATA_UPDATE job type

Revision ID: aedcba8d6c2c
Revises: b54692997717
Create Date: 2026-05-10 07:04:35.536985

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aedcba8d6c2c"
down_revision: Union[str, Sequence[str], None] = "b54692997717"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("original_title", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("overview", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("backdrop_path", sa.String(), nullable=True))
    op.add_column(
        "movies", sa.Column("tmdb_metadata_fetched_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("ALTER TYPE syncjobtype ADD VALUE IF NOT EXISTS 'TMDB_MOVIES_METADATA_UPDATE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "tmdb_metadata_fetched_at")
    op.drop_column("movies", "backdrop_path")
    op.drop_column("movies", "overview")
    op.drop_column("movies", "original_title")
    # ### end Alembic commands ###
