"""add_watch_status_and_movie_fields

Revision ID: b54692997717
Revises: 01760f85b906
Create Date: 2026-04-11 07:23:25.380654

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b54692997717"
down_revision: Union[str, Sequence[str], None] = "01760f85b906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    watchstatus_enum = sa.Enum("PLANNED", "WATCHING", "WATCHED", "DROPPED", name="watchstatus")
    watchstatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("movies", sa.Column("poster_url", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("movies", sa.Column("genres", sa.JSON(), nullable=True))
    op.add_column("movies", sa.Column("rating_value", sa.Float(), nullable=True))
    op.add_column("movies", sa.Column("rating_votes", sa.Integer(), nullable=True))
    op.add_column(
        "watch_history",
        sa.Column(
            "status",
            sa.Enum("PLANNED", "WATCHING", "WATCHED", "DROPPED", name="watchstatus"),
            nullable=False,
            server_default="PLANNED",
        ),
    )
    op.add_column(
        "watch_history",
        sa.Column("is_manual", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "watch_history", sa.Column("playback_position_ticks", sa.BigInteger(), nullable=True)
    )
    op.drop_column("watch_history", "is_watched")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watch_history",
        sa.Column(
            "is_watched",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.drop_column("watch_history", "playback_position_ticks")
    op.drop_column("watch_history", "is_manual")
    op.drop_column("watch_history", "status")
    sa.Enum(name="watchstatus").drop(op.get_bind(), checkfirst=True)
    op.drop_column("movies", "rating_votes")
    op.drop_column("movies", "rating_value")
    op.drop_column("movies", "genres")
    op.drop_column("movies", "year")
    op.drop_column("movies", "poster_url")
    # ### end Alembic commands ###
