"""update models for movies add status and delete watch

Revision ID: b6b882c23f9d
Revises: 379e67d12bb9
Create Date: 2025-11-03 19:20:36.667527

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6b882c23f9d"
down_revision: Union[str, Sequence[str], None] = "379e67d12bb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("status", sa.String(), nullable=True))
    op.drop_column("movies", "watched")
    op.drop_column("movies", "watched_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "watched_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column("movies", sa.Column("watched", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("movies", "status")
    # ### end Alembic commands ###
