"""update serias added  tmdb_id field

Revision ID: bb500f0431b8
Revises: f6b2a4f56a9f
Create Date: 2025-11-07 18:23:14.552421

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb500f0431b8"
down_revision: Union[str, Sequence[str], None] = "f6b2a4f56a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("series", sa.Column("tmdb_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "series", ["tmdb_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "series", type_="unique")
    op.drop_column("series", "tmdb_id")
    # ### end Alembic commands ###
