"""update models for watch history updated and is_watched and index fields

Revision ID: cc15243728fb
Revises: 5e69e8ebe3ea
Create Date: 2025-12-30 14:58:43.851810

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc15243728fb"
down_revision: Union[str, Sequence[str], None] = "5e69e8ebe3ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("watch_history", sa.Column("is_watched", sa.Boolean(), nullable=False))
    op.add_column(
        "watch_history",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "watch_history",
        "watched_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_index(
        op.f("ix_watch_history_episode_id"), "watch_history", ["episode_id"], unique=False
    )
    op.create_index(op.f("ix_watch_history_media_id"), "watch_history", ["media_id"], unique=False)
    op.create_index(op.f("ix_watch_history_user_id"), "watch_history", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_watch_state", "watch_history", ["user_id", "media_id", "episode_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_watch_state", "watch_history", type_="unique")
    op.drop_index(op.f("ix_watch_history_user_id"), table_name="watch_history")
    op.drop_index(op.f("ix_watch_history_media_id"), table_name="watch_history")
    op.drop_index(op.f("ix_watch_history_episode_id"), table_name="watch_history")
    op.alter_column(
        "watch_history",
        "watched_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("watch_history", "updated_at")
    op.drop_column("watch_history", "is_watched")
    # ### end Alembic commands ###
