"""add imdb_id to series

Revision ID: e0e03248ff4a
Revises: 844e6abd66a2
Create Date: 2025-10-19 07:11:20.176379

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0e03248ff4a"
down_revision: Union[str, Sequence[str], None] = "844e6abd66a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("sonarr_id", sa.Integer(), nullable=False))
    op.add_column("episodes", sa.Column("overview", sa.String(), nullable=True))
    op.create_unique_constraint(None, "episodes", ["sonarr_id"])
    op.add_column("series", sa.Column("imdb_id", sa.String(), nullable=True))
    op.add_column("series", sa.Column("poster_url", sa.String(), nullable=True))
    op.add_column("series", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("series", sa.Column("genres", sa.JSON(), nullable=True))
    op.add_column("series", sa.Column("rating_value", sa.Float(), nullable=True))
    op.add_column("series", sa.Column("rating_votes", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "series", ["imdb_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "series", type_="unique")
    op.drop_column("series", "rating_votes")
    op.drop_column("series", "rating_value")
    op.drop_column("series", "genres")
    op.drop_column("series", "year")
    op.drop_column("series", "poster_url")
    op.drop_column("series", "imdb_id")
    op.drop_constraint(None, "episodes", type_="unique")
    op.drop_column("episodes", "overview")
    op.drop_column("episodes", "sonarr_id")
    # ### end Alembic commands ###
