"""update series and seasons and episodes, added tvdb id and imdb and del watched fields

Revision ID: f6b2a4f56a9f
Revises: b6b882c23f9d
Create Date: 2025-11-04 13:11:34.008207

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6b2a4f56a9f"
down_revision: Union[str, Sequence[str], None] = "b6b882c23f9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episodes", "watched")
    op.drop_column("episodes", "watched_at")
    op.drop_column("seasons", "started_at")
    op.drop_column("seasons", "finished_at")
    op.add_column("series", sa.Column("tvdb_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "series", ["tvdb_id"])
    op.drop_column("series", "started_at")
    op.drop_column("series", "finished_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "series",
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "series",
        sa.Column(
            "started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "series", type_="unique")
    op.drop_column("series", "tvdb_id")
    op.add_column(
        "seasons",
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "seasons",
        sa.Column(
            "started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "episodes",
        sa.Column(
            "watched_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "episodes", sa.Column("watched", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
